pklSetUI() { 													; EPKL Settings GUI
	global UI_MainLay, UI_LayType, UI_KbdType, UI_LayMods
	global UI_LayMenu, UI_LayFile, UI_Btn 						; GUI Control vars must be global (or static) to work
	
	pklAppName  := getPklInfo( "pklName" )
	winTitle    := "EPKL Settings"
	anyTxt      := "<any>"
	layTypes    := [ anyTxt, "Colemak-eD", "Colemak-VK", "Dvorak", "QUARTZ", "QWERTY", "Tarmak" ] 	; eD WIP: Read this from the dir instead
	kbdTypes    := [ anyTxt, "ANS", "ISO" ]
	
	layName  := pklIniRead( "layoutName", locUnknown, "LayIni", "information" )
	layFile  := StrReplace( getPklInfo( "File_LayIni" ), "layout.ini", "" )
	basFile  :=             getPklInfo( "File_BasIni" )
	
	if WinActive( winTitle ) { 									; Toggle the GUI off if it's the active window
		GUI, UI: Destroy
		Return
	}
	;;  For a list of AHK GUI Controls, see https://www.autohotkey.com/docs/commands/GuiControls.htm
	GUI, UI:New,       , %winTitle%
	GUI, UI:Add, Tab3, , % "Layout" ;||Keys|Settings 				; eD WIP: Other settings
	
	GUI, UI:Add, Text, , % "Layout Selector for " . pklAppName
	GUI, UI:Add, Text, , ————————————————————————————————————————————————
	_uiAddSel( "Main layout: "          , "UI_MainLay", "Choose1"   , layTypes          )
	_uiAddSel( "Locale & layout type: " , "UI_LayType", "Choose1"   , [ "eD", "VK" ]    )
	_uiAddSel( "Keyboard type: "        , "UI_KbdType", "Choose1"   , kbdTypes          )
	_uiAddSel( "Mods, if any: "         , "UI_LayMods", "Choose1"   , layMods           )
	_uiAddEdt( "`nMenu name:"           , "UI_LayMenu", ""          , layName           )
	_uiAddEdt( "`nlayout = "            , "UI_LayFile", ""          , layFile "`n"      )
	GUI, UI:Add, Text, , 
	GUI, UI:Add, Button, gUIsel vUI_Btn Default, &Submit Override
	
	GUI, UI:Show
}

UIsel: 															; Routine for handling UI selections
	GUI, UI:Submit, Nohide
;	GUI, +LastFound
	GUIControl, , UI_LayFile, % UI_LayType . "`n" . UI_KbdType
Return

_uiAddEdt( intro, var, opts, editTxt ) { 		; Add an Edit box with text
	GUI, UI:Add, Text, , %intro%
	GUI, UI:Add, Edit, v%var% %opts%, % editTxt
}

_uiAddSel( intro, var, opts, listArr ) { 		; Add a DropDownList selection box with text and some choices
	For ix, elem in listArr { 						; Convert the array to a pipe delimited list
		pipe        := ( listStr ) ? "|" : ""
		listStr     .= pipe . elem
	} 	; end For
	GUI, UI:Add, Text, , %intro%
	GUI, UI:Add, DDL , gUIsel v%var% %opts%, % listStr
} 	; end fn

_uiWriteOverride( layLine ) {
/*
	overrideHeader :=
(
;
;;  =====================================================================================================================
;;  EPKL settings .ini file for EPiKaL PortableKeyboardLayout by Øystein Bech Gadmar a.k.a. DreymaR
;;    - For more info, see the EPKL repo at https://github.com/DreymaR/BigBagKbdTrixPKL
;;    - NOTE: This Layouts Override file was generated by EPKL. There's also an override example file you can look at.
;;  =====================================================================================================================
;

[pkl]
;;  NOTE: Only the first active layout line in this section will be used. Lines starting with a semicolon are inactive.


[layout]

)
*/ 	; eD WIP: Make a template instead, in Files?
	
} 	; end fn
